#!/usr/bin/env python3
"""
aidev monitor — checks tickets in RUNNING state; when the tmux pane shows the
AIDEV_TASK_COMPLETE marker (or goes idle), moves them to POSTPROCESS: pushes
the branch, opens a PR via gh, and posts a summary comment back to Jira.

Also checks tickets in STUCK state; when Claude printed AIDEV_NEEDS_INPUT it
posts the question as a Jira comment and waits. Once a human replies on the
ticket (a comment that isn't one of aidev's own [aidev]-style comments), the
reply text is typed into the tmux session so Claude can continue.

Run this from cron (e.g. every 2-3 minutes), separate from pickup.py.
"""
import os
import re
import subprocess
import sys
import uuid
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import codex_runner, config, jira_client, state, procs, lockfile, github
from lib.pipelog import get_logger
from lib.notify import notify
from lib.soul import soul_section, jira_live_fetch_note

log = get_logger("monitor")

COMPLETE_RE = re.compile(r"(?m)^\s*AIDEV_TASK_COMPLETE\s*$")
NEEDS_INPUT_RE = re.compile(r"(?m)^\s*AIDEV_NEEDS_INPUT:\s*(.+)$")


def is_complete(pane):
    return bool(COMPLETE_RE.search(pane))


def find_needs_input(pane):
    """Returns the most recent real AIDEV_NEEDS_INPUT question in the pane,
    or None. Filters out the instructional placeholder line echoed from the
    task prompt itself (contains the literal '<your question' template)."""
    matches = [m.strip() for m in NEEDS_INPUT_RE.findall(pane) if "<your question" not in m]
    return matches[-1] if matches else None


def open_pr(ticket):
    cfg = config.load()
    worktree_path = ticket["worktree_path"]
    branch = ticket["branch"]
    key = ticket["ticket_key"]

    # Defense in depth: .aidev_prompt.txt lives under .claude-code/ now (see
    # relaunch_claude/pickup.py), but if it's tracked from an older run or a
    # future bug re-adds it at the repo root, strip it before it ships in a PR.
    procs.sh("git rm --cached --ignore-unmatch .aidev_prompt.txt .claude-code/.aidev_prompt.txt",
             cwd=worktree_path, check=False, timeout=60)

    # Make sure everything is committed (Claude was instructed to commit,
    # but double-check / catch stragglers).
    # Big repos (large node_modules + husky pre-commit/lint-staged) can push
    # `git add`/`git commit`/`git push` well past the default 60s timeout —
    # give these a 10-minute budget instead of procs.sh's default.
    procs.sh("git add -A", cwd=worktree_path, check=False, timeout=600)
    status = procs.sh("git status --porcelain", cwd=worktree_path, check=False, timeout=600)
    if status:
        msg = procs.shlex.quote(f"{key}: wip changes captured by aidev monitor")
        procs.sh(f"git commit -m {msg}", cwd=worktree_path, check=False, timeout=600)

    procs.sh(f"git push -u origin {branch}", cwd=worktree_path, check=False, timeout=600)

    # Normal case now: Claude opens its own PR (with a real title/description)
    # before printing AIDEV_TASK_COMPLETE — reuse it rather than creating a
    # second one.
    existing = procs.sh(
        f"gh pr view {branch} --json url --jq .url", cwd=worktree_path, check=False
    )
    if existing and existing.startswith("https://"):
        return existing.strip(), f"reused existing PR: {existing.strip()}"

    # Fallback only: Claude should have opened this itself. If we're here,
    # something went wrong upstream — this placeholder unblocks the pipeline
    # but is not the intended path; check why Claude didn't open its own PR.
    log(f"{key}: no PR found after implement — Claude should have opened one; falling back to a placeholder PR")
    base = ticket.get("stacked_on_branch") or cfg["pr"]["base_branch"]
    title = f"{key}: automated by aidev"
    body = (
        f"Automated implementation for {key}.\n\n"
        f"Generated by Claude Code via aidev pipeline. This PR was opened by the "
        f"orchestrator's fallback, not by Claude itself — that's unexpected; the task "
        f"prompt instructs Claude to open its own PR with a real description."
    )
    if ticket.get("stacked_on"):
        body += (
            f"\n\nStacked on {ticket['stacked_on']} (still In Review at PR open time) — "
            f"this PR's diff includes {ticket['stacked_on']}'s changes until that one merges. "
            f"Rebase onto {cfg['pr']['base_branch']} after {ticket['stacked_on']} lands."
        )
    pr_out = procs.sh(
        f'gh pr create --base {base} --head {branch} --title {procs.shlex.quote(title)} '
        f'--body {procs.shlex.quote(body)}',
        cwd=worktree_path, check=False,
    )
    pr_url = None
    for line in pr_out.splitlines():
        if line.startswith("https://"):
            pr_url = line.strip()
    return pr_url, pr_out


def mark_failed(key, reason, tmux_name=None):
    log(f"{key}: FAILED — {reason}")
    state.set_state(key, "FAILED")
    try:
        jira_client.add_comment(key, f"[aidev] Marked as failed: {reason}")
        jira_client.set_state_label(key, "aidev-stuck")
    except Exception as e:
        log(f"{key}: could not post failure comment: {e}")
    if tmux_name:
        procs.tmux_kill(tmux_name)
    notify(f"aidev: {key} failed", reason, key=key)


def process_running_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while RUNNING (crash, reboot, or manual kill)")
        return

    if not procs.claude_process_alive(tmux_name):
        mark_failed(
            key,
            "tmux session is alive but the claude process inside it is not — it crashed or exited "
            "(e.g. an unhandled API error) without finishing. The session's pane output up to that "
            "point may still be useful context for a human or for a manual relaunch.",
        )
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"exceeded max_running_hours ({max_hours}h) — likely stuck in a loop or blocked silently",
            tmux_name=tmux_name,
        )
        return

    pane = procs.tmux_capture(tmux_name, lines=300)

    if is_complete(pane):
        log(f"{key}: task complete marker seen, waiting for idle before postprocess")
        procs.wait_for_idle(
            tmux_name,
            cfg["claude"]["idle_seconds"],
            cfg["claude"]["idle_poll_interval"],
            max_wait_seconds=300,
        )
        finish_ticket(ticket)
        return

    question = find_needs_input(pane)
    if question:
        log(f"{key}: needs input — {question}")
        state.set_stuck(key, question)
        try:
            jira_client.add_comment(
                key,
                f"[aidev] I need input to continue:\n\n{question}\n\n"
                f"Reply on this ticket and I'll pick it up on the next check.",
            )
            jira_client.set_state_label(key, "aidev-stuck")
        except Exception as e:
            log(f"{key}: could not post stuck comment: {e}")
        notify(f"aidev: {key} needs input", question, key=key, pr_url=ticket.get("pr_url"))
        return

    log(f"{key}: still running")


def finish_ticket(ticket):
    """Called when a RUNNING Claude session prints AIDEV_TASK_COMPLETE and
    goes idle. What happens next depends on ticket['stage']:
    - 'implement' (the normal first pass): push, open the PR (once — every
      later stage just pushes to it), then relaunch Claude for 'self_review'
      so /simplify, /custom-simplify, /custom-review run against a PR that
      actually exists (custom-review tags it ai-reviewed and needs a real
      PR number — running it before the PR existed silently no-op'd this).
    - 'self_review': push whatever Claude changed, then run Codex as a
      non-critical second opinion (see lib/codex_runner) and relaunch Claude
      only if Codex left real findings; otherwise hand off to human review
      directly. Bugbot does NOT run here — it runs once, at auto-merge time
      (right before the PR actually lands in master), not on every review
      pass, since a PR can sit in human review for a long time and running
      it here too would just mean running it twice for the same commit.
    - 'codex_check' (Claude just addressed Codex's findings, if any): push,
      hand off to human review.
    - 'auto_merge*' (Claude just resolved a conflict or fixed a Bugbot
      finding as part of the auto-merge sequence): push, then re-enter the
      auto-merge check from the top (see continue_auto_merge).
    """
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_attempts = cfg["claude"].get("max_postprocess_attempts", 5)
    stage = ticket.get("stage") or "implement"

    state.set_state(key, "POSTPROCESS")
    log(f"{key}: pushing / opening PR (stage={stage})")
    try:
        pr_url, pr_out = open_pr(ticket)
    except Exception as e:
        attempts = ticket.get("postprocess_attempts", 0) + 1
        if attempts >= max_attempts:
            mark_failed(
                key,
                f"PR step failed after {attempts} attempts: {e}",
                tmux_name=tmux_name,
            )
        else:
            # Transient failure (e.g. a slow git commit/push in a big repo
            # blowing past a subprocess timeout) — the work is already
            # committed in the worktree, so just retry next run. Do NOT
            # kill the tmux session: a live pane is what lets a human
            # `tmux attach` and intervene, and killing it here would make
            # any future STUCK/rework flow for this ticket impossible.
            state.record_postprocess_failure(key, e)
            log(f"{key}: PR step failed (attempt {attempts}/{max_attempts}), will retry: {e}")
        return

    state.clear_postprocess_failure(key)

    if not pr_url:
        mark_review_done(ticket, pr_url, pr_out)
        return

    if stage == "implement":
        relaunch_for_stage(ticket, "self_review", pr_url,
                            build_self_review_prompt, notice="running self-review (/simplify, "
                            "/custom-simplify, /custom-review) now that the PR exists")
        return

    if stage == "self_review":
        run_codex_stage(ticket, pr_url)
        return

    if stage.startswith("auto_merge"):
        continue_auto_merge(ticket, pr_url)
        return

    mark_review_done(ticket, pr_url, pr_out)


def relaunch_for_stage(ticket, next_stage, pr_url, prompt_builder, notice=None):
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["summary"])
        summary = issue["fields"]["summary"]
    except Exception:
        summary = key
    prompt = prompt_builder(key, summary, pr_url)
    session_id = relaunch_claude(ticket, prompt)
    with state.db() as conn:
        conn.execute(
            "UPDATE tickets SET session_id = ? WHERE ticket_key = ?",
            (session_id, key),
        )
    state.set_stage(key, next_stage)
    state.reopen_for_rework(key)
    log(f"{key}: relaunched Claude for stage={next_stage} (session {session_id})")
    try:
        extra = f"\n{notice}." if notice else ""
        jira_client.add_comment(
            key,
            f"[aidev] PR: {pr_url}{extra}\nSession ID: {session_id}",
        )
    except Exception as e:
        log(f"{key}: could not post stage-transition comment: {e}")


def run_codex_stage(ticket, pr_url):
    """Non-critical: Codex's success/failure never blocks the pipeline. On
    any failure (disabled, not installed, timeout, no credits, bad output)
    this logs and hands off to human review, same as if Codex had reported
    no findings — Bugbot itself now only runs at auto-merge time (right
    before the PR actually lands in master), not here, to avoid running it
    twice for the same commit across a possibly-long review wait."""
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["summary"])
        summary = issue["fields"]["summary"]
    except Exception:
        summary = key

    ok, report_rel, detail = codex_runner.run_codex_review(ticket, key, summary, log=log)
    if not ok:
        log(f"{key}: codex review skipped ({detail}) — handing off to human review")
        mark_review_done(ticket, pr_url)
        return

    report_abs = os.path.join(ticket["worktree_path"], report_rel)
    try:
        with open(report_abs) as f:
            report_text = f.read()
    except OSError as e:
        log(f"{key}: codex report unreadable ({e}) — handing off to human review")
        mark_review_done(ticket, pr_url)
        return

    if re.search(r"^##\s*Verdict:\s*CLEAN\b", report_text, re.MULTILINE):
        log(f"{key}: codex review clean — handing off to human review")
        mark_review_done(ticket, pr_url)
        return

    log(f"{key}: codex review left findings at {report_rel} — relaunching Claude")

    def prompt_builder(key, summary, pr_url):
        return build_codex_findings_prompt(key, summary, pr_url, report_rel, report_text)

    relaunch_for_stage(ticket, "codex_check", pr_url, prompt_builder,
                        notice=f"a second reviewer (Codex) left notes at {report_rel} — "
                        f"Claude is reading them now")


def build_self_review_prompt(key, summary, pr_url):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    return f"""{soul_section()}You just finished implementing Jira ticket {key}: {summary}, and the
orchestrator has pushed your branch and opened the PR: {pr_url}

Now run your own review pass on the diff, in order:
{steps}

`/custom-review` needs a real PR to tag and comment on — it now has one
({pr_url}), which is why this runs as its own pass instead of before the PR
existed. Commit and push again if you make any changes (same worktree/branch
— do not open a new PR).

Before finishing, post your decisions log as its own PR comment: read
`.claude-code/decisions-{key}.md` (if it doesn't exist, you made no notable
judgment calls — skip this) and `gh pr comment {pr_url} --body '...'` with it
formatted per the "Post a decisions log as its own PR comment" section above
(aidev decisions / My decisions).

When done, say exactly: AIDEV_TASK_COMPLETE
"""


def build_codex_findings_prompt(key, summary, pr_url, report_rel, report_text):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    return f"""{soul_section()}You are addressing a second reviewer's findings on Jira ticket {key}: {summary}.

This ticket already has an open PR: {pr_url}
You are in the same worktree and branch as before — the existing implementation
is already committed and pushed. Do NOT start over or create a new branch.

Codex (a lower-budget second-opinion reviewer, not authoritative) left this
report at `{report_rel}`:

---
{report_text}
---

Use your own judgment, the same way you would for a human reviewer's comment:
fix what's real, and say explicitly in the commit message why you're leaving
anything you disagree with or consider out of scope. Codex cannot edit code
itself — this report is advisory only.

When done, run these steps in order:
{steps}
Stage and commit ALL changes with a clear commit message that references
{key}, then push to the existing branch (this updates the existing PR
automatically — do not open a new PR). If you made no changes because
there was nothing to fix, that's fine — just say so plainly.

When done, say exactly: AIDEV_TASK_COMPLETE
"""


def mark_review_done(ticket, pr_url, pr_out=None):
    """Hand off to a human: Jira comment, status transition, label, DONE
    state, kill the now-unneeded tmux session."""
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]

    state.set_state(key, "PR_OPENED", pr_url=pr_url)

    comment_lines = [f"\u2705 aidev finished {key}."]
    if pr_url:
        comment_lines.append(f"PR: {pr_url}")
    elif pr_out:
        comment_lines.append(f"PR step output:\n{pr_out}")
    comment_lines.append(f"Worktree: {ticket['worktree_path']}")
    comment_lines.append(f"Session ID: {ticket['session_id']}")
    jira_client.add_comment(key, "\n".join(comment_lines))

    try:
        jira_client.transition_issue(key, cfg["jira"]["review_status"])
    except RuntimeError as e:
        log(f"{key}: transition warning: {e}")
    try:
        jira_client.set_state_label(key, "aidev-done")
    except Exception as e:
        log(f"{key}: label warning: {e}")

    state.set_state(key, "DONE", pr_url=pr_url)
    state.set_stage(key, "implement")  # reset for any future rework cycle
    procs.tmux_kill(tmux_name)
    log(f"{key}: done")
    notify(f"aidev: {key} done", "PR opened" if pr_url else "PR step had no URL — check comment",
           key=key, pr_url=pr_url)


def process_stuck_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while STUCK (crash, reboot, or manual kill)")
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"stuck waiting for a reply past max_running_hours ({max_hours}h) with no response",
            tmux_name=tmux_name,
        )
        return

    try:
        comments = jira_client.get_comments(key)
    except Exception as e:
        log(f"{key}: could not fetch comments: {e}")
        return

    if not comments:
        return

    last = comments[-1]
    body_text = jira_client.plain_description({"fields": {"description": last["body"]}})
    if body_text.strip().startswith("[aidev]"):
        # Last comment is our own — no human reply yet.
        return

    last_seen = ticket.get("last_comment_id")
    if last_seen == last["id"]:
        return

    log(f"{key}: human reply found — resuming session with the reply")
    procs.tmux_send(tmux_name, body_text.replace("\n", " "))
    state.set_last_comment_id(key, last["id"])
    state.clear_stuck(key)
    try:
        jira_client.set_state_label(key, "aidev-picked")
    except Exception as e:
        log(f"{key}: label warning: {e}")


def relaunch_claude(ticket, prompt):
    """Starts a fresh Claude Code session in the ticket's existing worktree/
    branch (used for rework after human review feedback). Returns the new
    session_id."""
    worktree_path = ticket["worktree_path"]
    tmux_name = ticket["tmux_session"]
    cfg = config.load()
    session_id = str(uuid.uuid4())

    if procs.tmux_session_exists(tmux_name):
        procs.tmux_kill(tmux_name)
    procs.tmux_new_session(tmux_name)

    prompt_file = os.path.join(worktree_path, ".claude-code", ".aidev_prompt.txt")
    os.makedirs(os.path.dirname(prompt_file), exist_ok=True)
    with open(prompt_file, "w") as f:
        f.write(prompt)

    skip_perms = "--dangerously-skip-permissions" if cfg["claude"]["dangerously_skip_permissions"] else ""
    claude_cmd = (
        f"cd {worktree_path} && "
        f"DISABLE_AUTOUPDATER=1 claude --session-id {session_id} {skip_perms} "
        f"\"$(cat .claude-code/.aidev_prompt.txt)\""
    )
    procs.tmux_send(tmux_name, claude_cmd)
    return session_id


def build_rework_prompt(key, summary, feedback, pr_url):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    link = f"{config.load()['jira']['base_url']}/browse/{key}"
    live_fetch_note = jira_live_fetch_note(key, link)
    return f"""{soul_section()}You are addressing human review feedback on Jira ticket {key}: {summary}
Link: {link}

This ticket already has an open PR: {pr_url}
You are in the same worktree and branch as before — the existing implementation
is already committed and pushed. Do NOT start over or create a new branch.

{live_fetch_note}
Reviewer feedback (embedded snapshot — fallback only, see note above):
{feedback}

If the original ticket referenced shared context files (repo root's
`.claude-code/`, Notion pages via `/notion`, Slack links), re-check them for
anything the feedback might relate to, and keep appending any new
decisions/learnings there — repo root's `.claude-code/`, not this worktree's
(it gets deleted on cleanup), never overwrite existing content, only add.

Task:
- Make the changes needed to address the feedback above, in this worktree.
- When done, run these steps in order:
{steps}
- Stage and commit ALL changes with a clear commit message that references {key}.
- Then push to the existing branch (this updates the existing PR automatically
  — do not open a new PR).
- Add a line to the PR (a new comment, or fold into the commit message)
  stating which Jira source you worked from: "Jira context: live-fetched
  via <tool>" or "Jira context: pipeline's embedded snapshot only (could
  not live-fetch: <reason>)".

If you are blocked and need clarification, follow the same batching rule as
the main implementation stage (see "`AIDEV_NEEDS_INPUT` fires at most once
per ticket" above): research, keep working with a provisional answer, log to
`.claude-code/decisions-{key}.md`, and only print one batched
`AIDEV_NEEDS_INPUT` at the end if anything is still open.

When you are fully done, committed, and pushed, say exactly: AIDEV_TASK_COMPLETE
"""


def gather_rework_feedback(ticket):
    """Collects new review feedback from both Jira and the PR's GitHub
    comments since this ticket last went DONE, and returns it as one
    combined text block (or None if there's nothing new on either side).

    Jira comment authored by us always starts "[aidev]"/"\u2705" (existing
    convention); on GitHub the equivalent is the decisions-log comment,
    which always starts "**aidev decisions" (see SOUL.md's "Post a decisions
    log" section) \u2014 both are filtered out as our own output, not feedback.
    A handful of routine bot/automation authors are filtered too so a
    `@bugbot run` trigger comment or a CI bot post doesn't masquerade as
    human feedback."""
    key = ticket["ticket_key"]
    since = ticket.get("updated_at")  # last time this ticket's state changed (i.e. went DONE)

    jira_feedback = None
    try:
        issue = jira_client.get_issue(key, fields=["comment"])
        for c in reversed(issue["fields"]["comment"]["comments"]):
            text = jira_client.plain_description({"fields": {"description": c["body"]}})
            if not text.strip().startswith("[aidev]") and not text.strip().startswith("\u2705"):
                jira_feedback = text
                break
    except Exception as e:
        log(f"{key}: could not fetch Jira comments for rework check: {e}")

    github_feedback = None
    try:
        pr_comments = github.get_pr_comments(ticket["repo_path"], ticket.get("pr_url"))
        bot_authors = {"github-actions", "cursor", "cursor-ai", "dependabot", "sonarqubecloud"}
        since_dt = None
        if since:
            try:
                since_dt = datetime.strptime(since, "%Y-%m-%d %H:%M:%S")
            except ValueError:
                pass
        for c in reversed(pr_comments):
            author = (c.get("author") or {}).get("login", "")
            body = (c.get("body") or "").strip()
            created_at = c.get("createdAt", "")
            if since_dt and created_at:
                try:
                    created_dt = datetime.strptime(created_at, "%Y-%m-%dT%H:%M:%SZ")
                    if created_dt <= since_dt:
                        break  # comments come oldest-first; nothing older is new
                except ValueError:
                    pass  # unparseable timestamp — don't skip on the strength of a bad date
            if author.lower() in bot_authors:
                continue
            if body.startswith("**aidev decisions") or body.startswith("@bugbot"):
                continue
            if not body:
                continue
            github_feedback = f"(from {author} on the GitHub PR)\n{body}"
            break
    except Exception as e:
        log(f"{key}: could not fetch PR comments for rework check: {e}")

    parts = [p for p in (jira_feedback, github_feedback) if p]
    return "\n\n---\n\n".join(parts) if parts else None


def process_done_ticket(ticket):
    """DONE tickets whose Jira status was manually moved back to
    in_progress_status are review-feedback re-opens: relaunch Claude in the
    same worktree/branch to address the feedback, then land back on
    review_status + aidev-done via the normal finish_ticket path."""
    cfg = config.load()
    key = ticket["ticket_key"]

    try:
        issue = jira_client.get_issue(key, fields=["status", "summary"])
    except Exception as e:
        log(f"{key}: could not fetch issue for rework check: {e}")
        return

    current_status = issue["fields"]["status"]["name"]
    if current_status.lower() != cfg["jira"]["in_progress_status"].lower():
        return  # still In Review / Done / whatever — nothing to do

    log(f"{key}: moved back to {current_status} after DONE — treating as rework request")

    feedback = gather_rework_feedback(ticket)
    if not feedback:
        feedback = "(No specific comment found — re-review the PR and address anything outstanding.)"

    summary = issue["fields"]["summary"]
    prompt = build_rework_prompt(key, summary, feedback, ticket.get("pr_url") or "")

    session_id = relaunch_claude(ticket, prompt)
    with state.db() as conn:
        conn.execute(
            "UPDATE tickets SET session_id = ? WHERE ticket_key = ?",
            (session_id, key),
        )
    state.reopen_for_rework(key)

    try:
        jira_client.add_comment(
            key,
            f"[aidev] Picked up your feedback, resuming work in the same worktree/branch.\n"
            f"Session ID: {session_id}",
        )
        jira_client.set_state_label(key, "aidev-picked")
    except Exception as e:
        log(f"{key}: could not post rework comment: {e}")

    notify(f"aidev: {key} rework started", feedback[:200], key=key, pr_url=ticket.get("pr_url"))


AUTO_MERGE_LABEL = "aidev-auto-merge"
REQUIRED_LABEL = "ai-reviewed"


def escalate_auto_merge(ticket, reason, waiting_on_human=False):
    """Stops the auto-merge sequence and tells the human why. When
    `waiting_on_human` is True this is a pause, not a dead end — Cursor
    itself deferred to a human GitHub review (its own judgment call, not
    something fixable by pushing code), so the ticket stays DONE with stage
    `auto_merge_waiting_human` and every future DONE-sweep cycle re-checks
    whether that approval landed, resuming automatically the moment it has.
    Anything else genuinely can't proceed without a person looking at it, so
    the label is removed — re-tag `aidev-auto-merge` once it's addressed to
    try again, same as tagging a ticket in the first place."""
    key = ticket["ticket_key"]
    log(f"{key}: auto-merge {'waiting on human review' if waiting_on_human else 'stuck'} — {reason}")
    try:
        jira_client.add_comment(
            key,
            f"[aidev] auto-merge {'paused, waiting on a human GitHub review' if waiting_on_human else 'stuck'}: {reason}",
        )
    except Exception as e:
        log(f"{key}: could not post auto-merge status comment: {e}")
    if waiting_on_human:
        state.set_stage(key, "auto_merge_waiting_human")
    else:
        try:
            jira_client.remove_label(key, AUTO_MERGE_LABEL)
        except Exception as e:
            log(f"{key}: could not remove {AUTO_MERGE_LABEL} label: {e}")
        state.set_stage(key, "implement")  # back to the normal DONE baseline
    # Belt-and-suspenders: every caller of process_auto_merge_ticket expects
    # to operate on a DONE ticket (that's what the sweep iterates), but a
    # caller reached via continue_auto_merge may have come from POSTPROCESS
    # — make sure escalating never silently drops the ticket out of DONE.
    state.set_state(key, "DONE")
    notify(f"aidev: {key} auto-merge {'waiting on human' if waiting_on_human else 'stuck'}", reason[:200],
           key=key, pr_url=ticket.get("pr_url"))


def build_auto_merge_conflict_prompt(key, summary, pr_url):
    return f"""{soul_section()}You are resolving a merge conflict so Jira ticket {key}: {summary}'s PR
({pr_url}) can merge to master as part of an auto-merge sequence. You are in
the same worktree/branch as before — the existing implementation is already
committed and pushed. Do NOT start over or create a new branch.

`git merge origin/master` in this worktree and resolve any conflicts. Prefer
keeping both sides where the conflicting hunks are genuinely independent
additions (e.g. two unrelated fields added near each other) — that is the
common case for a stacked PR whose sibling branches merged ahead of it.
Verify the resolution actually builds/typechecks before committing (this
repo's own convention — `npm run type:check` or equivalent). If the conflict
is semantically ambiguous (the two sides changed the same behavior in
different, incompatible ways) do NOT guess — print exactly:
AIDEV_NEEDS_INPUT: <describe the ambiguous conflict, one line>
and stop.

Otherwise, commit the resolution and push to the existing branch (this
updates the existing PR — do not open a new PR), then say exactly:
AIDEV_TASK_COMPLETE
"""


def build_auto_merge_bugbot_fix_prompt(key, summary, pr_url, bugbot_review_text):
    return f"""{soul_section()}You are addressing a Cursor Bugbot finding on Jira ticket {key}: {summary}'s
PR ({pr_url}), as part of an auto-merge sequence. You are in the same
worktree/branch as before — the existing implementation is already committed
and pushed. Do NOT start over or create a new branch.

Bugbot's latest review on this PR:
---
{bugbot_review_text}
---

Fix what's real, same judgment as any other Bugbot pass — explain in the
commit message why you're leaving anything you disagree with or consider a
false positive, rather than silently ignoring it. Resolve the GitHub review
threads for whatever you addressed (see the "Cursor Bugbot" section above
for the `gh api graphql` commands).

Commit and push to the existing branch (this updates the existing PR — do
not open a new PR), then say exactly: AIDEV_TASK_COMPLETE
"""


def build_auto_merge_approval_prompt(key, summary, pr_url, verdict_text):
    return f"""{soul_section()}You are handling Cursor's Approval Agent verdict on Jira ticket {key}: {summary}'s
PR ({pr_url}), as part of an auto-merge sequence. You are in the same
worktree/branch as before — the existing implementation is already committed
and pushed. Do NOT start over or create a new branch.

Cursor's latest Approval Agent verdict on this PR (NOT an approval):
---
{verdict_text}
---

Use your own judgment reading this verdict, the same way you'd read a human
reviewer's comment — there is no fixed rule for what this text says, Cursor's
wording varies run to run. In particular: a human reviewer being assigned to
the PR (e.g. "reviewers assigned", "reviewers were already assigned") is NOT
by itself a reason to stop — Cursor itself still approves plenty of PRs that
have an assigned reviewer (see e.g. PR #5789 for a real example: assigned +
still approved shortly after on a repeat verdict). Only treat a human
reviewer as required if the verdict explicitly says human review is
mandatory/already required with no further automated path (e.g. it names a
completed/pending human sign-off as the only remaining step, not just that
someone was tagged in passing).

- If the verdict tells you to run something (the custom-review skill, a
  fresh Bugbot pass, etc.) and you haven't already done that for the
  current commit, do it now — the same custom-review/custom-simplify skills
  from earlier stages are available to you here.
- If the verdict already reflects work you've done (e.g. you already ran
  custom-review for this exact commit), or names nothing actionable, just
  comment `/approve` again to get a fresh verdict.
- Only if the verdict unambiguously states that a human review is required
  and already exists/is pending as the sole remaining path (not just "a
  reviewer is assigned" in passing) — do not comment `/approve` again, and
  instead print exactly:
AIDEV_NEEDS_INPUT: <quote the part of the verdict that says human review is required>
  and stop.

Otherwise, once you've taken whatever action applies (running a skill,
committing/pushing if you changed anything, commenting `/approve`), say
exactly: AIDEV_TASK_COMPLETE
"""


def _latest_review_matching(pr_details, marker):
    """Returns the most recent review (by submission order, which is what
    `gh pr view --json reviews` returns) whose body contains `marker`, or
    None. Cursor posts both Bugbot and Approval Agent verdicts as reviews
    from the same `cursor` author, so the body marker — not the author — is
    what actually distinguishes them (`BUGBOT_REVIEW` vs `Cursor Approval
    Agent`)."""
    matches = [r for r in pr_details.get("reviews", []) if marker in (r.get("body") or "")]
    return matches[-1] if matches else None


_BUGBOT_COMMIT_RE = re.compile(r"for commit ([0-9a-f]{7,40})")


def _bugbot_review_commit(review):
    """Extracts the commit SHA Bugbot's review body says it reviewed (its
    boilerplate footer: "Reviewed by Cursor Bugbot for commit <sha>."), or
    None if not found."""
    if not review:
        return None
    m = _BUGBOT_COMMIT_RE.search(review.get("body") or "")
    return m.group(1) if m else None


_REVIEW_PASS_COMMIT_RE = re.compile(r"commits? (?:up to )?\b([0-9a-f]{7,40})\b")


def _custom_review_covers_head(repo_path, pr_url, branch, head_sha):
    """The `ai-reviewed` label (unlike Bugbot's review comment) carries no
    commit SHA — GitHub labels aren't tied to a commit, so once applied it
    stays applied forever even after new commits land (e.g. a conflict
    resolution push in the middle of an auto-merge run). Caught live: Cursor's
    own Approval Agent correctly refused to approve a PR with a stale
    `ai-reviewed` label and asked for /custom-review to be re-run — this
    mirrors that same judgment in our own gate instead of trusting the label
    alone.

    Finds our own last "aidev decisions: ... commit(s) [up to] <sha>" PR
    comment (posted by the self_review/codex_check prompts) and requires
    that reviewed commit to be EXACTLY the PR's current head — not merely an
    ancestor of it. Ancestor-or-equal would be backwards here: if the
    reviewed commit is an ancestor of head, head necessarily has MORE,
    unreviewed commits on top of it (e.g. this same auto-merge run's own
    conflict-resolution push) — that's precisely the stale case, not a
    covered one. No matching comment counts as NOT covering head —
    conservative by design, a false "needs re-review" is cheap (one extra
    Claude pass) but a false "clean" would ship an unreviewed commit."""
    if not head_sha:
        return False
    comments = github.get_pr_comments(repo_path, pr_url)
    review_comments = [c for c in comments if (c.get("body") or "").startswith("**aidev decisions")]
    if not review_comments:
        return False
    last = review_comments[-1]
    m = _REVIEW_PASS_COMMIT_RE.search(last.get("body") or "")
    if not m:
        return False
    reviewed_sha = m.group(1)
    return head_sha.startswith(reviewed_sha)


def _last_approve_request_time(repo_path, pr_url):
    """Returns the createdAt of the most recent `/approve` PR comment (ours
    or anyone's — only aidev and humans post this convention), or None if
    it's never been requested."""
    comments = github.get_pr_comments(repo_path, pr_url)
    approve_comments = [c for c in comments if (c.get("body") or "").strip() == "/approve"]
    return approve_comments[-1]["createdAt"] if approve_comments else None


def build_auto_merge_ci_failure_prompt(key, summary, pr_url, failed_checks):
    checks_block = "\n".join(
        f"- {c['name']}: {c.get('conclusion') or c.get('status') or 'unknown'}"
        + (f" ({c['detailsUrl']})" if c.get("detailsUrl") else "")
        for c in failed_checks
    )
    changelog_hint = ""
    if any("changelog" in (c.get("name") or "").lower() for c in failed_checks):
        changelog_hint = """
Note: the "changelog" check is failing. That one specifically means this PR
touches source files with no changelog entry and isn't tagged `no-changelog`.
Use your own judgment on the actual diff: if the change is genuinely
customer-facing, add a real entry (`npm run changelog` or equivalent, check
`.agents/rules/changelog.md` if unsure of format); if it's internal/test/
tooling-only and too small to matter to users, tag the PR yourself
(`gh pr edit {pr_url} --add-label no-changelog`) with a one-line reason in a
PR comment. Don't guess if it's genuinely ambiguous — see below.
"""
    return f"""{soul_section()}You are addressing failing CI checks on Jira ticket {key}: {summary}'s
PR ({pr_url}), as part of an auto-merge sequence. You are in the same
worktree/branch as before — the existing implementation is already committed
and pushed. Do NOT start over or create a new branch.

These checks are currently failing (red, not just pending):
{checks_block}
{changelog_hint}
Use your own judgment, the same way you would investigate any CI failure —
read the actual failure output (`gh run view` / the check's details URL,
whatever applies) before touching anything. Common cases:
- A genuine test/lint/type failure caused by your own change — fix it.
- A flaky/unrelated failure (infra hiccup, a pre-existing failure on master
  unrelated to this diff) — do not just retry blindly; if you're confident
  it's unrelated, note that in a PR comment and leave it, since re-triggering
  a workflow run isn't necessarily something you can do from here.
- The changelog check — see the note above.

If you fix something, commit and push to the existing branch (this updates
the existing PR — do not open a new PR). If you're genuinely unsure what a
failure means or how to address it, do not guess — print exactly:
AIDEV_NEEDS_INPUT: <one line: which check, what's unclear>
and stop.

Otherwise, once you've taken whatever action applies, say exactly:
AIDEV_TASK_COMPLETE
"""


def _classify_checks(pr_details):
    """Splits statusCheckRollup into (red, pending) — green/skipped/neutral
    checks are dropped entirely, they need no action. A check with no
    conclusion yet (still running/queued) is pending, not failing — this
    pipeline should never treat "not done yet" as "broken"; only an
    explicit non-success conclusion counts as red and worth Claude's
    attention."""
    red, pending = [], []
    for c in pr_details.get("statusCheckRollup", []):
        conclusion = (c.get("conclusion") or "").upper()
        status = (c.get("status") or "").upper()
        if conclusion in ("SUCCESS", "SKIPPED", "NEUTRAL"):
            continue
        if not conclusion and status and status != "COMPLETED":
            pending.append(c)
            continue
        if conclusion in ("FAILURE", "ERROR", "CANCELLED", "TIMED_OUT", "ACTION_REQUIRED", "STARTUP_FAILURE"):
            red.append(c)
        else:
            pending.append(c)
    return red, pending


def process_auto_merge_ticket(ticket):
    """DONE tickets tagged `aidev-auto-merge` — see the skill's "Auto-merge
    a stacked PR chain" section for the full design and why. Runs entirely
    off `gh`/git; only spins up a Claude session (via relaunch_claude, same
    as the rework loop) for the two sub-steps that genuinely need judgment:
    resolving a real merge conflict, and fixing a real Bugbot finding.
    Everything else here is mechanical and safe to retry every cycle."""
    key = ticket["ticket_key"]
    pr_url = ticket.get("pr_url")
    repo_path = ticket["repo_path"]
    branch = ticket["branch"]

    try:
        cfg = config.load()
        issue = jira_client.get_issue(key, fields=["status", "labels"])
        status_name = issue["fields"]["status"]["name"]
        labels = issue["fields"]["labels"]
    except Exception as e:
        log(f"{key}: could not check status/labels for auto-merge: {e}")
        return
    if AUTO_MERGE_LABEL not in labels:
        return
    # Never act on a ticket that isn't genuinely done and handed off —
    # `state.all_in_state("DONE")` reflects the local state DB, which could
    # in principle drift from Jira (a rework got triggered concurrently, a
    # human moved it manually); re-verify against Jira itself before ever
    # touching the PR. Running work must never be auto-merged.
    if status_name.lower() != cfg["jira"]["review_status"].lower() or "aidev-done" not in labels:
        log(f"{key}: auto-merge label present but ticket is not In Review + aidev-done "
            f"(status={status_name}, labels={labels}) — skipping, not touching running work")
        return

    if not pr_url:
        escalate_auto_merge(ticket, "no PR URL recorded for this ticket")
        return

    details = github.get_pr_details(repo_path, pr_url)
    if not details:
        log(f"{key}: could not fetch PR details this cycle, will retry")
        return

    if details["baseRefName"] != "master":
        log(f"{key}: auto-merge — base is {details['baseRefName']}, not master yet, skipping")
        return

    log(f"{key}: auto-merge — base is master, proceeding")

    # --- conflict check -------------------------------------------------
    if details["mergeable"] == "CONFLICTING" or details["mergeStateStatus"] == "DIRTY":
        log(f"{key}: auto-merge — merge conflict, relaunching Claude to resolve")
        relaunch_for_stage(ticket, "auto_merge_resolving_conflict", pr_url, build_auto_merge_conflict_prompt,
                            notice="auto-merge hit a conflict with master — resolving it")
        return

    # --- bugbot loop ------------------------------------------------------
    # Bugbot's own "clean" marker text, and its "real findings" text, both
    # live in the comment body — see SOUL.md's Cursor Bugbot section for the
    # exact conventions this mirrors. A "clean" review only counts if it was
    # actually run against the PR's CURRENT head commit — Bugbot's review
    # comment embeds the SHA it reviewed ("...for commit <sha>."), and a
    # push since then (e.g. this same sequence's own conflict-resolution
    # commit) makes an old clean verdict stale and worthless as a safety
    # check. Without this, a real bug: resolving a conflict, pushing a new
    # commit, then treating yesterday's "clean" Bugbot review of the
    # pre-conflict-fix commit as still valid.
    head_sha = details.get("headRefOid", "")
    latest_bugbot = _latest_review_matching(details, "BUGBOT_REVIEW")
    bugbot_reviewed_current_head = (
        bool(latest_bugbot)
        and bool(head_sha)
        and head_sha.startswith(_bugbot_review_commit(latest_bugbot) or "\0")
    )
    bugbot_clean = (
        bugbot_reviewed_current_head
        and "found no new issues" in (latest_bugbot.get("body") or "").lower()
    )
    bugbot_findings_text = (
        latest_bugbot.get("body") if bugbot_reviewed_current_head and not bugbot_clean else None
    )
    if bugbot_findings_text:
        log(f"{key}: auto-merge — Bugbot left findings, relaunching Claude to address them")
        def prompt_builder(key, summary, pr_url, _text=bugbot_findings_text):
            return build_auto_merge_bugbot_fix_prompt(key, summary, pr_url, _text)
        relaunch_for_stage(ticket, "auto_merge_fixing_bugbot", pr_url, prompt_builder,
                            notice="auto-merge — Bugbot left findings, fixing them")
        return

    if not bugbot_clean:
        # The "Cursor Bugbot" entry in statusCheckRollup is a real CI check
        # (not the review-comment text) with its own status/timestamps — use
        # that instead of guessing a fixed re-trigger timeout. Bugbot's own
        # response time varies a lot in practice (observed 5-28+ minutes
        # between a manual "@bugbot run" and its reply across past PRs), so
        # a flat 15-minute timer risks re-triggering while it's still
        # legitimately running (yellow/IN_PROGRESS), which just restarts the
        # wait and can loop. Only re-trigger if the check itself is not
        # currently in progress.
        bugbot_check = next(
            (c for c in details.get("statusCheckRollup", []) if c.get("name") == "Cursor Bugbot"),
            None,
        )
        bugbot_check_running = bool(bugbot_check) and (bugbot_check.get("status") or "").upper() in (
            "IN_PROGRESS", "QUEUED", "PENDING", "REQUESTED", "WAITING",
        )
        already_triggered = ticket.get("last_bugbot_trigger_sha") == head_sha
        if already_triggered and bugbot_check_running:
            log(f"{key}: auto-merge — Bugbot check still running for {head_sha[:8]}, waiting")
            return  # give it more time; re-checked next cycle, no re-trigger
        # Fallback for when there's no matching check at all (e.g. it hasn't
        # started yet, or the workflow name changes) — a time-based backstop
        # so this can't wait forever with nothing to poll.
        trigger_stale = True
        if already_triggered and not bugbot_check and ticket.get("last_bugbot_trigger_at"):
            try:
                triggered_at = datetime.strptime(ticket["last_bugbot_trigger_at"], "%Y-%m-%d %H:%M:%S")
                trigger_stale = (datetime.utcnow() - triggered_at).total_seconds() > 1800  # 30 min
            except ValueError:
                pass
        if already_triggered and not bugbot_check and not trigger_stale:
            log(f"{key}: auto-merge — already triggered Bugbot for {head_sha[:8]}, no check visible yet, waiting")
            return
        log(f"{key}: auto-merge — Bugbot hasn't reviewed the current commit yet, triggering it"
            + (" (re-trigger: not running per its check, or no response after 30min)" if already_triggered else ""))
        try:
            github.comment_on_pr(repo_path, pr_url, "@bugbot run")
            state.set_last_bugbot_trigger_sha(key, head_sha)
        except Exception as e:
            escalate_auto_merge(ticket, f"could not trigger Bugbot: {e}")
        return  # give it time; re-checked next cycle

    # --- gate checks --------------------------------------------------
    label_names = {l["name"] for l in details.get("labels", [])}
    if REQUIRED_LABEL not in label_names:
        escalate_auto_merge(
            ticket,
            f"PR missing the '{REQUIRED_LABEL}' label — /custom-review may not have run. Not safe to auto-merge without it.",
        )
        return

    if not _custom_review_covers_head(repo_path, pr_url, branch, details.get("headRefOid", "")):
        log(f"{key}: auto-merge — '{REQUIRED_LABEL}' label is stale (commits landed since the "
            f"last /custom-review pass, e.g. a conflict-resolution push) — re-running review")
        relaunch_for_stage(ticket, "auto_merge_recheck", pr_url, build_self_review_prompt,
                            notice="auto-merge — re-running /custom-review, PR changed since the last pass")
        return

    # --- CI checks: red is Claude's to judge, yellow is just a wait ------
    # No hardcoded "changelog specifically means X" branch here — a check
    # being red (failing tests, lint, changelog enforcer, anything) is not
    # automatically "stuck"; Claude reads the actual failures and decides
    # what to do, same non-deterministic pattern as the Bugbot/approval
    # gates. Only a check still queued/running is a genuine "wait, not
    # broken" — never treated as needing Claude's attention.
    red_checks, pending_checks = _classify_checks(details)
    if red_checks:
        log(f"{key}: auto-merge — {len(red_checks)} check(s) red "
            f"({', '.join(c['name'] for c in red_checks)}), relaunching Claude to judge them")
        def ci_prompt_builder(key, summary, pr_url, _checks=red_checks):
            return build_auto_merge_ci_failure_prompt(key, summary, pr_url, _checks)
        relaunch_for_stage(ticket, "auto_merge_fixing_ci", pr_url, ci_prompt_builder,
                            notice=f"auto-merge — {len(red_checks)} CI check(s) red, judging and addressing them")
        return
    if pending_checks:
        log(f"{key}: auto-merge — {len(pending_checks)} check(s) still running "
            f"({', '.join(c['name'] for c in pending_checks)}), waiting")
        return

    # --- approval ---------------------------------------------------------
    approved = any(r.get("state") == "APPROVED" for r in details.get("reviews", []))

    if approved:
        log(f"{key}: auto-merge — approved, merging")
        ok, out = github.merge_pr(repo_path, pr_url)
        if not ok:
            escalate_auto_merge(ticket, f"merge failed: {out}")
            return
        try:
            jira_client.transition_issue(key, "Done")
        except Exception as e:
            log(f"{key}: could not transition to Done after merge: {e}")
        try:
            jira_client.add_comment(key, f"[aidev] Merged: {pr_url}")
        except Exception as e:
            log(f"{key}: could not post merge comment: {e}")
        state.set_stage(key, "implement")
        notify(f"aidev: {key} auto-merged", "Merged to base branch", key=key, pr_url=pr_url)
        return

    if details.get("reviewRequests"):
        log(f"{key}: auto-merge — reviewer(s) assigned "
            f"({', '.join(r.get('login', '?') for r in details['reviewRequests'])}), "
            f"still trying /approve — an assigned reviewer alone doesn't block Cursor's own approval")

    latest_approval_verdict = _latest_review_matching(details, "Approval Agent")
    verdict_body = (latest_approval_verdict.get("body") or "") if latest_approval_verdict else ""

    last_request = _last_approve_request_time(repo_path, pr_url)
    verdict_is_current = (
        last_request
        and latest_approval_verdict
        and latest_approval_verdict.get("submittedAt", "") > last_request
    )
    bugbot_newer_than_verdict = (
        verdict_is_current
        and latest_bugbot
        and latest_bugbot.get("submittedAt", "") > latest_approval_verdict.get("submittedAt", "")
    )
    if verdict_is_current and not bugbot_newer_than_verdict:
        # We already asked since the last relevant change and got a non-approval
        # answer. Don't parse the wording ourselves (Cursor's phrasing varies
        # run to run, and a regex here already caused a real miss: "assign" was
        # meant to catch genuine human-deferral verdicts but also matched
        # "reviewers will be assigned", which is routine boilerplate, not a
        # deferral). Hand the verdict text to Claude and let it judge — same
        # pattern as the Bugbot-findings relaunch above.
        log(f"{key}: auto-merge — non-approval verdict, relaunching Claude to read and act on it")
        def approval_prompt_builder(key, summary, pr_url, _text=verdict_body):
            return build_auto_merge_approval_prompt(key, summary, pr_url, _text)
        relaunch_for_stage(ticket, "auto_merge_addressing_approval_feedback", pr_url, approval_prompt_builder,
                            notice="auto-merge — Cursor did not approve, reading its verdict and acting on it")
        return

    log(f"{key}: auto-merge — requesting Cursor approval")
    try:
        github.comment_on_pr(repo_path, pr_url, "/approve")
    except Exception as e:
        escalate_auto_merge(ticket, f"could not comment /approve: {e}")
    return  # give it time; re-checked next cycle


def continue_auto_merge(ticket, pr_url):
    """Called from finish_ticket when a relaunched auto-merge Claude session
    (conflict resolution, a Bugbot fix, or a stale-review re-check) finishes.
    Re-enters the same check from the top — the push it just did will be
    reflected in the next `gh pr view`.

    Must restore state to DONE first: finish_ticket already set it to
    POSTPROCESS (its very first line) by the time we're called, and nothing
    else on this path ever sets it back. Caught live: RND-14813 silently
    dropped out of every future `state.all_in_state("DONE")` auto-merge
    sweep after its conflict-resolution relaunch, since it was sitting in
    PR_OPENED, not DONE, and the sweep only iterates DONE tickets."""
    key = ticket["ticket_key"]
    state.set_state(key, "DONE", pr_url=pr_url)
    ticket = state.get(key)
    state.set_stage(key, "auto_merge_recheck")
    process_auto_merge_ticket(ticket)


def cleanup_worktree(ticket):
    """Removes the git worktree and local branch for a ticket. Safe to call
    even if the worktree is already gone. Never touches the remote branch —
    that's GitHub's PR-merge cleanup, not ours."""
    key = ticket["ticket_key"]
    repo_path = ticket["repo_path"]
    worktree_path = ticket["worktree_path"]
    branch = ticket["branch"]
    tmux_name = ticket["tmux_session"]

    procs.tmux_kill(tmux_name)

    if os.path.isdir(worktree_path):
        result = procs.sh(f"git worktree remove {procs.shlex.quote(worktree_path)} --force", cwd=repo_path, check=False)
        log(f"{key}: removed worktree at {worktree_path}")
    else:
        log(f"{key}: worktree already gone at {worktree_path}")

    procs.sh(f"git branch -D {procs.shlex.quote(branch)}", cwd=repo_path, check=False)
    procs.sh("git worktree prune", cwd=repo_path, check=False)


TERMINAL_JIRA_STATUSES = ("done", "rejected", "cancelled", "closed")


def process_cleanup_candidate(ticket):
    """Checks whether a tracked ticket has reached a terminal Jira status
    (Done/Rejected/etc, set by a human — the pipeline never sets these) and,
    if so, removes its worktree/branch and archives it in the state DB so
    disk usage doesn't grow unbounded across weeks of tickets."""
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["status"])
    except Exception as e:
        log(f"{key}: could not check status for cleanup: {e}")
        return

    status_name = issue["fields"]["status"]["name"]
    if status_name.lower() not in TERMINAL_JIRA_STATUSES:
        return

    log(f"{key}: Jira status is '{status_name}' — cleaning up worktree and archiving")
    cleanup_worktree(ticket)
    state.set_archived(key)


def main():
    try:
        with lockfile.Lock("monitor"):
            _run()
    except lockfile.LockHeld as e:
        log(f"skip run: {e}")


def _run():
    running = state.all_in_state("RUNNING")
    log(f"Checking {len(running)} running ticket(s)")
    for ticket in running:
        try:
            process_running_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing {ticket['ticket_key']}: {e}")

    postprocess = state.all_in_state("POSTPROCESS")
    log(f"Checking {len(postprocess)} postprocess ticket(s) for PR retry")
    for ticket in postprocess:
        try:
            finish_ticket(ticket)
        except Exception as e:
            log(f"ERROR retrying postprocess {ticket['ticket_key']}: {e}")

    stuck = state.all_in_state("STUCK")
    log(f"Checking {len(stuck)} stuck ticket(s) for human replies")
    for ticket in stuck:
        try:
            process_stuck_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing stuck {ticket['ticket_key']}: {e}")

    done = state.all_in_state("DONE")
    log(f"Checking {len(done)} done ticket(s) for review re-opens")
    for ticket in done:
        try:
            process_done_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing done {ticket['ticket_key']}: {e}")

    auto_merge_candidates = state.all_in_state("DONE")
    log(f"Checking {len(auto_merge_candidates)} done ticket(s) for auto-merge")
    for ticket in auto_merge_candidates:
        try:
            process_auto_merge_ticket(ticket)
        except Exception as e:
            log(f"ERROR auto-merging {ticket['ticket_key']}: {e}")

    candidates = state.all_cleanup_candidates()
    log(f"Checking {len(candidates)} ticket(s) for worktree cleanup (terminal Jira status)")
    for ticket in candidates:
        try:
            process_cleanup_candidate(ticket)
        except Exception as e:
            log(f"ERROR cleaning up {ticket['ticket_key']}: {e}")


if __name__ == "__main__":
    main()
