#!/usr/bin/env python3
"""
aidev monitor — checks tickets in RUNNING state; when the tmux pane shows the
AIDEV_TASK_COMPLETE marker (or goes idle), moves them to POSTPROCESS: pushes
the branch, opens a PR via gh, and posts a summary comment back to Jira.

Also checks tickets in STUCK state; when Claude printed AIDEV_NEEDS_INPUT it
posts the question as a Jira comment and waits. Once a human replies on the
ticket (a comment that isn't one of aidev's own [aidev]-style comments), the
reply text is typed into the tmux session so Claude can continue.

Run this from cron (e.g. every 2-3 minutes), separate from pickup.py.
"""
import os
import re
import subprocess
import sys
import uuid

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import codex_runner, config, jira_client, state, procs, lockfile
from lib.pipelog import get_logger
from lib.notify import notify
from lib.soul import soul_section

log = get_logger("monitor")

COMPLETE_RE = re.compile(r"(?m)^\s*AIDEV_TASK_COMPLETE\s*$")
NEEDS_INPUT_RE = re.compile(r"(?m)^\s*AIDEV_NEEDS_INPUT:\s*(.+)$")


def is_complete(pane):
    return bool(COMPLETE_RE.search(pane))


def find_needs_input(pane):
    """Returns the most recent real AIDEV_NEEDS_INPUT question in the pane,
    or None. Filters out the instructional placeholder line echoed from the
    task prompt itself (contains the literal '<your question' template)."""
    matches = [m.strip() for m in NEEDS_INPUT_RE.findall(pane) if "<your question" not in m]
    return matches[-1] if matches else None


def open_pr(ticket):
    cfg = config.load()
    worktree_path = ticket["worktree_path"]
    branch = ticket["branch"]
    key = ticket["ticket_key"]

    # Defense in depth: .aidev_prompt.txt lives under .claude-code/ now (see
    # relaunch_claude/pickup.py), but if it's tracked from an older run or a
    # future bug re-adds it at the repo root, strip it before it ships in a PR.
    procs.sh("git rm --cached --ignore-unmatch .aidev_prompt.txt .claude-code/.aidev_prompt.txt",
             cwd=worktree_path, check=False, timeout=60)

    # Make sure everything is committed (Claude was instructed to commit,
    # but double-check / catch stragglers).
    # Big repos (large node_modules + husky pre-commit/lint-staged) can push
    # `git add`/`git commit`/`git push` well past the default 60s timeout —
    # give these a 10-minute budget instead of procs.sh's default.
    procs.sh("git add -A", cwd=worktree_path, check=False, timeout=600)
    status = procs.sh("git status --porcelain", cwd=worktree_path, check=False, timeout=600)
    if status:
        msg = procs.shlex.quote(f"{key}: wip changes captured by aidev monitor")
        procs.sh(f"git commit -m {msg}", cwd=worktree_path, check=False, timeout=600)

    procs.sh(f"git push -u origin {branch}", cwd=worktree_path, check=False, timeout=600)

    # Normal case now: Claude opens its own PR (with a real title/description)
    # before printing AIDEV_TASK_COMPLETE — reuse it rather than creating a
    # second one.
    existing = procs.sh(
        f"gh pr view {branch} --json url --jq .url", cwd=worktree_path, check=False
    )
    if existing and existing.startswith("https://"):
        return existing.strip(), f"reused existing PR: {existing.strip()}"

    # Fallback only: Claude should have opened this itself. If we're here,
    # something went wrong upstream — this placeholder unblocks the pipeline
    # but is not the intended path; check why Claude didn't open its own PR.
    log(f"{key}: no PR found after implement — Claude should have opened one; falling back to a placeholder PR")
    base = ticket.get("stacked_on_branch") or cfg["pr"]["base_branch"]
    title = f"{key}: automated by aidev"
    body = (
        f"Automated implementation for {key}.\n\n"
        f"Generated by Claude Code via aidev pipeline. This PR was opened by the "
        f"orchestrator's fallback, not by Claude itself — that's unexpected; the task "
        f"prompt instructs Claude to open its own PR with a real description."
    )
    if ticket.get("stacked_on"):
        body += (
            f"\n\nStacked on {ticket['stacked_on']} (still In Review at PR open time) — "
            f"this PR's diff includes {ticket['stacked_on']}'s changes until that one merges. "
            f"Rebase onto {cfg['pr']['base_branch']} after {ticket['stacked_on']} lands."
        )
    pr_out = procs.sh(
        f'gh pr create --base {base} --head {branch} --title {procs.shlex.quote(title)} '
        f'--body {procs.shlex.quote(body)}',
        cwd=worktree_path, check=False,
    )
    pr_url = None
    for line in pr_out.splitlines():
        if line.startswith("https://"):
            pr_url = line.strip()
    return pr_url, pr_out


def mark_failed(key, reason, tmux_name=None):
    log(f"{key}: FAILED — {reason}")
    state.set_state(key, "FAILED")
    try:
        jira_client.add_comment(key, f"[aidev] Marked as failed: {reason}")
        jira_client.set_state_label(key, "aidev-stuck")
    except Exception as e:
        log(f"{key}: could not post failure comment: {e}")
    if tmux_name:
        procs.tmux_kill(tmux_name)
    notify(f"aidev: {key} failed", reason)


def process_running_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while RUNNING (crash, reboot, or manual kill)")
        return

    if not procs.claude_process_alive(tmux_name):
        mark_failed(
            key,
            "tmux session is alive but the claude process inside it is not — it crashed or exited "
            "(e.g. an unhandled API error) without finishing. The session's pane output up to that "
            "point may still be useful context for a human or for a manual relaunch.",
        )
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"exceeded max_running_hours ({max_hours}h) — likely stuck in a loop or blocked silently",
            tmux_name=tmux_name,
        )
        return

    pane = procs.tmux_capture(tmux_name, lines=300)

    if is_complete(pane):
        log(f"{key}: task complete marker seen, waiting for idle before postprocess")
        procs.wait_for_idle(
            tmux_name,
            cfg["claude"]["idle_seconds"],
            cfg["claude"]["idle_poll_interval"],
            max_wait_seconds=300,
        )
        finish_ticket(ticket)
        return

    question = find_needs_input(pane)
    if question:
        log(f"{key}: needs input — {question}")
        state.set_stuck(key, question)
        try:
            jira_client.add_comment(
                key,
                f"[aidev] I need input to continue:\n\n{question}\n\n"
                f"Reply on this ticket and I'll pick it up on the next check.",
            )
            jira_client.set_state_label(key, "aidev-stuck")
        except Exception as e:
            log(f"{key}: could not post stuck comment: {e}")
        notify(f"aidev: {key} needs input", question)
        return

    log(f"{key}: still running")


def finish_ticket(ticket):
    """Called when a RUNNING Claude session prints AIDEV_TASK_COMPLETE and
    goes idle. What happens next depends on ticket['stage']:
    - 'implement' (the normal first pass): push, open the PR (once — every
      later stage just pushes to it), then relaunch Claude for 'self_review'
      so /simplify, /custom-simplify, /custom-review run against a PR that
      actually exists (custom-review tags it ai-reviewed and needs a real
      PR number — running it before the PR existed silently no-op'd this).
    - 'self_review': push whatever Claude changed, then run Codex as a
      non-critical second opinion (see lib/codex_runner) and relaunch Claude
      only if Codex left real findings; otherwise skip straight to Bugbot.
    - 'codex_check' (Claude just addressed Codex's findings, if any): push,
      go to Bugbot.
    - 'bugbot_check' (Claude just finished looking at Bugbot, possibly after
      fixing something and pushing): push whatever's there, then hand off to
      human review. No text parsing of Bugbot's output happens here — Claude
      already made that judgment call before printing AIDEV_TASK_COMPLETE.
    """
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_attempts = cfg["claude"].get("max_postprocess_attempts", 5)
    stage = ticket.get("stage") or "implement"

    state.set_state(key, "POSTPROCESS")
    log(f"{key}: pushing / opening PR (stage={stage})")
    try:
        pr_url, pr_out = open_pr(ticket)
    except Exception as e:
        attempts = ticket.get("postprocess_attempts", 0) + 1
        if attempts >= max_attempts:
            mark_failed(
                key,
                f"PR step failed after {attempts} attempts: {e}",
                tmux_name=tmux_name,
            )
        else:
            # Transient failure (e.g. a slow git commit/push in a big repo
            # blowing past a subprocess timeout) — the work is already
            # committed in the worktree, so just retry next run. Do NOT
            # kill the tmux session: a live pane is what lets a human
            # `tmux attach` and intervene, and killing it here would make
            # any future STUCK/rework flow for this ticket impossible.
            state.record_postprocess_failure(key, e)
            log(f"{key}: PR step failed (attempt {attempts}/{max_attempts}), will retry: {e}")
        return

    state.clear_postprocess_failure(key)

    if not pr_url:
        mark_review_done(ticket, pr_url, pr_out)
        return

    if stage == "implement":
        relaunch_for_stage(ticket, "self_review", pr_url,
                            build_self_review_prompt, notice="running self-review (/simplify, "
                            "/custom-simplify, /custom-review) now that the PR exists")
        return

    if stage == "self_review":
        run_codex_stage(ticket, pr_url)
        return

    if stage == "codex_check":
        relaunch_for_stage(ticket, "bugbot_check", pr_url, build_bugbot_check_prompt)
        return

    mark_review_done(ticket, pr_url, pr_out)


def relaunch_for_stage(ticket, next_stage, pr_url, prompt_builder, notice=None):
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["summary"])
        summary = issue["fields"]["summary"]
    except Exception:
        summary = key
    prompt = prompt_builder(key, summary, pr_url)
    session_id = relaunch_claude(ticket, prompt)
    with state.db() as conn:
        conn.execute(
            "UPDATE tickets SET session_id = ? WHERE ticket_key = ?",
            (session_id, key),
        )
    state.set_stage(key, next_stage)
    state.reopen_for_rework(key)
    log(f"{key}: relaunched Claude for stage={next_stage} (session {session_id})")
    try:
        extra = f"\n{notice}." if notice else ""
        jira_client.add_comment(
            key,
            f"[aidev] PR: {pr_url}{extra}\nSession ID: {session_id}",
        )
    except Exception as e:
        log(f"{key}: could not post stage-transition comment: {e}")


def run_codex_stage(ticket, pr_url):
    """Non-critical: Codex's success/failure never blocks the pipeline. On
    any failure (disabled, not installed, timeout, no credits, bad output)
    this logs and skips straight to the Bugbot stage, same as if Codex had
    reported no findings."""
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["summary"])
        summary = issue["fields"]["summary"]
    except Exception:
        summary = key

    ok, report_rel, detail = codex_runner.run_codex_review(ticket, key, summary, log=log)
    if not ok:
        log(f"{key}: codex review skipped ({detail}) — proceeding to Bugbot")
        relaunch_for_stage(ticket, "bugbot_check", pr_url, build_bugbot_check_prompt)
        return

    report_abs = os.path.join(ticket["worktree_path"], report_rel)
    try:
        with open(report_abs) as f:
            report_text = f.read()
    except OSError as e:
        log(f"{key}: codex report unreadable ({e}) — proceeding to Bugbot")
        relaunch_for_stage(ticket, "bugbot_check", pr_url, build_bugbot_check_prompt)
        return

    if re.search(r"^##\s*Verdict:\s*CLEAN\b", report_text, re.MULTILINE):
        log(f"{key}: codex review clean — proceeding to Bugbot")
        relaunch_for_stage(ticket, "bugbot_check", pr_url, build_bugbot_check_prompt)
        return

    log(f"{key}: codex review left findings at {report_rel} — relaunching Claude")

    def prompt_builder(key, summary, pr_url):
        return build_codex_findings_prompt(key, summary, pr_url, report_rel, report_text)

    relaunch_for_stage(ticket, "codex_check", pr_url, prompt_builder,
                        notice=f"a second reviewer (Codex) left notes at {report_rel} — "
                        f"Claude is reading them now")


def build_self_review_prompt(key, summary, pr_url):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    return f"""{soul_section()}You just finished implementing Jira ticket {key}: {summary}, and the
orchestrator has pushed your branch and opened the PR: {pr_url}

Now run your own review pass on the diff, in order:
{steps}

`/custom-review` needs a real PR to tag and comment on — it now has one
({pr_url}), which is why this runs as its own pass instead of before the PR
existed. Commit and push again if you make any changes (same worktree/branch
— do not open a new PR).

Before finishing, post your decisions log as its own PR comment: read
`.claude-code/decisions-{key}.md` (if it doesn't exist, you made no notable
judgment calls — skip this) and `gh pr comment {pr_url} --body '...'` with it
formatted per the "Post a decisions log as its own PR comment" section above
(aidev decisions / My decisions).

When done, say exactly: AIDEV_TASK_COMPLETE
"""


def build_codex_findings_prompt(key, summary, pr_url, report_rel, report_text):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    return f"""{soul_section()}You are addressing a second reviewer's findings on Jira ticket {key}: {summary}.

This ticket already has an open PR: {pr_url}
You are in the same worktree and branch as before — the existing implementation
is already committed and pushed. Do NOT start over or create a new branch.

Codex (a lower-budget second-opinion reviewer, not authoritative) left this
report at `{report_rel}`:

---
{report_text}
---

Use your own judgment, the same way you would for a human reviewer's comment:
fix what's real, and say explicitly in the commit message why you're leaving
anything you disagree with or consider out of scope. Codex cannot edit code
itself — this report is advisory only.

When done, run these steps in order:
{steps}
Stage and commit ALL changes with a clear commit message that references
{key}, then push to the existing branch (this updates the existing PR
automatically — do not open a new PR). If you made no changes because
there was nothing to fix, that's fine — just say so plainly.

When done, say exactly: AIDEV_TASK_COMPLETE
"""


def build_bugbot_check_prompt(key, summary, pr_url):
    return f"""{soul_section()}You just finished implementing Jira ticket {key}: {summary}, and the
orchestrator has pushed your branch and opened the PR: {pr_url}

Now follow the "Cursor Bugbot" section above: check the PR's Bugbot review on
your current head commit, trigger it if it hasn't run yet, wait a reasonable
amount for it, and fix anything real it flags (commit + push again if you do
— you're in the same worktree/branch, don't open a new PR).

Do not touch anything unrelated to what Bugbot flagged; this is not a second
pass at the ticket's implementation.

When you're satisfied Bugbot is either clean or you've made a good-faith
effort and explained why anything outstanding is fine, say exactly: AIDEV_TASK_COMPLETE
"""


def mark_review_done(ticket, pr_url, pr_out=None):
    """Hand off to a human: Jira comment, status transition, label, DONE
    state, kill the now-unneeded tmux session."""
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]

    state.set_state(key, "PR_OPENED", pr_url=pr_url)

    comment_lines = [f"\u2705 aidev finished {key}."]
    if pr_url:
        comment_lines.append(f"PR: {pr_url}")
    elif pr_out:
        comment_lines.append(f"PR step output:\n{pr_out}")
    comment_lines.append(f"Worktree: {ticket['worktree_path']}")
    comment_lines.append(f"Session ID: {ticket['session_id']}")
    jira_client.add_comment(key, "\n".join(comment_lines))

    try:
        jira_client.transition_issue(key, cfg["jira"]["review_status"])
    except RuntimeError as e:
        log(f"{key}: transition warning: {e}")
    try:
        jira_client.set_state_label(key, "aidev-done")
    except Exception as e:
        log(f"{key}: label warning: {e}")

    state.set_state(key, "DONE", pr_url=pr_url)
    state.set_stage(key, "implement")  # reset for any future rework cycle
    procs.tmux_kill(tmux_name)
    log(f"{key}: done")
    notify(f"aidev: {key} done", pr_url or "PR step had no URL — check comment")


def process_stuck_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while STUCK (crash, reboot, or manual kill)")
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"stuck waiting for a reply past max_running_hours ({max_hours}h) with no response",
            tmux_name=tmux_name,
        )
        return

    try:
        comments = jira_client.get_comments(key)
    except Exception as e:
        log(f"{key}: could not fetch comments: {e}")
        return

    if not comments:
        return

    last = comments[-1]
    body_text = jira_client.plain_description({"fields": {"description": last["body"]}})
    if body_text.strip().startswith("[aidev]"):
        # Last comment is our own — no human reply yet.
        return

    last_seen = ticket.get("last_comment_id")
    if last_seen == last["id"]:
        return

    log(f"{key}: human reply found — resuming session with the reply")
    procs.tmux_send(tmux_name, body_text.replace("\n", " "))
    state.set_last_comment_id(key, last["id"])
    state.clear_stuck(key)
    try:
        jira_client.set_state_label(key, "aidev-picked")
    except Exception as e:
        log(f"{key}: label warning: {e}")


def relaunch_claude(ticket, prompt):
    """Starts a fresh Claude Code session in the ticket's existing worktree/
    branch (used for rework after human review feedback). Returns the new
    session_id."""
    worktree_path = ticket["worktree_path"]
    tmux_name = ticket["tmux_session"]
    cfg = config.load()
    session_id = str(uuid.uuid4())

    if procs.tmux_session_exists(tmux_name):
        procs.tmux_kill(tmux_name)
    procs.tmux_new_session(tmux_name)

    prompt_file = os.path.join(worktree_path, ".claude-code", ".aidev_prompt.txt")
    os.makedirs(os.path.dirname(prompt_file), exist_ok=True)
    with open(prompt_file, "w") as f:
        f.write(prompt)

    skip_perms = "--dangerously-skip-permissions" if cfg["claude"]["dangerously_skip_permissions"] else ""
    claude_cmd = (
        f"cd {worktree_path} && "
        f"DISABLE_AUTOUPDATER=1 claude --session-id {session_id} {skip_perms} "
        f"\"$(cat .claude-code/.aidev_prompt.txt)\""
    )
    procs.tmux_send(tmux_name, claude_cmd)
    return session_id


def build_rework_prompt(key, summary, feedback, pr_url):
    steps = "\n".join(
        f"{i+1}. Run the slash command: {s}"
        for i, s in enumerate(config.load()["claude"]["post_steps"])
    )
    return f"""{soul_section()}You are addressing human review feedback on Jira ticket {key}: {summary}

This ticket already has an open PR: {pr_url}
You are in the same worktree and branch as before — the existing implementation
is already committed and pushed. Do NOT start over or create a new branch.

Reviewer feedback to address:
{feedback}

If the original ticket referenced shared context files (repo root's
`.claude-code/`, Notion pages via `/notion`, Slack links), re-check them for
anything the feedback might relate to, and keep appending any new
decisions/learnings there — repo root's `.claude-code/`, not this worktree's
(it gets deleted on cleanup), never overwrite existing content, only add.

Task:
- Make the changes needed to address the feedback above, in this worktree.
- When done, run these steps in order:
{steps}
- Stage and commit ALL changes with a clear commit message that references {key}.
- Then push to the existing branch (this updates the existing PR automatically
  — do not open a new PR).

If you are blocked and need clarification, follow the same batching rule as
the main implementation stage (see "`AIDEV_NEEDS_INPUT` fires at most once
per ticket" above): research, keep working with a provisional answer, log to
`.claude-code/decisions-{key}.md`, and only print one batched
`AIDEV_NEEDS_INPUT` at the end if anything is still open.

When you are fully done, committed, and pushed, say exactly: AIDEV_TASK_COMPLETE
"""


def process_done_ticket(ticket):
    """DONE tickets whose Jira status was manually moved back to
    in_progress_status are review-feedback re-opens: relaunch Claude in the
    same worktree/branch to address the feedback, then land back on
    review_status + aidev-done via the normal finish_ticket path."""
    cfg = config.load()
    key = ticket["ticket_key"]

    try:
        issue = jira_client.get_issue(key, fields=["status", "summary", "comment"])
    except Exception as e:
        log(f"{key}: could not fetch issue for rework check: {e}")
        return

    current_status = issue["fields"]["status"]["name"]
    if current_status.lower() != cfg["jira"]["in_progress_status"].lower():
        return  # still In Review / Done / whatever — nothing to do

    log(f"{key}: moved back to {current_status} after DONE — treating as rework request")

    comments = issue["fields"]["comment"]["comments"]
    feedback = None
    for c in reversed(comments):
        text = jira_client.plain_description({"fields": {"description": c["body"]}})
        if not text.strip().startswith("[aidev]") and not text.strip().startswith("✅"):
            feedback = text
            break

    if not feedback:
        feedback = "(No specific comment found — re-review the PR and address anything outstanding.)"

    summary = issue["fields"]["summary"]
    prompt = build_rework_prompt(key, summary, feedback, ticket.get("pr_url") or "")

    session_id = relaunch_claude(ticket, prompt)
    with state.db() as conn:
        conn.execute(
            "UPDATE tickets SET session_id = ? WHERE ticket_key = ?",
            (session_id, key),
        )
    state.reopen_for_rework(key)

    try:
        jira_client.add_comment(
            key,
            f"[aidev] Picked up your feedback, resuming work in the same worktree/branch.\n"
            f"Session ID: {session_id}",
        )
        jira_client.set_state_label(key, "aidev-picked")
    except Exception as e:
        log(f"{key}: could not post rework comment: {e}")

    notify(f"aidev: {key} rework started", feedback[:200])


def cleanup_worktree(ticket):
    """Removes the git worktree and local branch for a ticket. Safe to call
    even if the worktree is already gone. Never touches the remote branch —
    that's GitHub's PR-merge cleanup, not ours."""
    key = ticket["ticket_key"]
    repo_path = ticket["repo_path"]
    worktree_path = ticket["worktree_path"]
    branch = ticket["branch"]
    tmux_name = ticket["tmux_session"]

    procs.tmux_kill(tmux_name)

    if os.path.isdir(worktree_path):
        result = procs.sh(f"git worktree remove {procs.shlex.quote(worktree_path)} --force", cwd=repo_path, check=False)
        log(f"{key}: removed worktree at {worktree_path}")
    else:
        log(f"{key}: worktree already gone at {worktree_path}")

    procs.sh(f"git branch -D {procs.shlex.quote(branch)}", cwd=repo_path, check=False)
    procs.sh("git worktree prune", cwd=repo_path, check=False)


TERMINAL_JIRA_STATUSES = ("done", "rejected", "cancelled", "closed")


def process_cleanup_candidate(ticket):
    """Checks whether a tracked ticket has reached a terminal Jira status
    (Done/Rejected/etc, set by a human — the pipeline never sets these) and,
    if so, removes its worktree/branch and archives it in the state DB so
    disk usage doesn't grow unbounded across weeks of tickets."""
    key = ticket["ticket_key"]
    try:
        issue = jira_client.get_issue(key, fields=["status"])
    except Exception as e:
        log(f"{key}: could not check status for cleanup: {e}")
        return

    status_name = issue["fields"]["status"]["name"]
    if status_name.lower() not in TERMINAL_JIRA_STATUSES:
        return

    log(f"{key}: Jira status is '{status_name}' — cleaning up worktree and archiving")
    cleanup_worktree(ticket)
    state.set_archived(key)


def main():
    try:
        with lockfile.Lock("monitor"):
            _run()
    except lockfile.LockHeld as e:
        log(f"skip run: {e}")


def _run():
    running = state.all_in_state("RUNNING")
    log(f"Checking {len(running)} running ticket(s)")
    for ticket in running:
        try:
            process_running_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing {ticket['ticket_key']}: {e}")

    postprocess = state.all_in_state("POSTPROCESS")
    log(f"Checking {len(postprocess)} postprocess ticket(s) for PR retry")
    for ticket in postprocess:
        try:
            finish_ticket(ticket)
        except Exception as e:
            log(f"ERROR retrying postprocess {ticket['ticket_key']}: {e}")

    stuck = state.all_in_state("STUCK")
    log(f"Checking {len(stuck)} stuck ticket(s) for human replies")
    for ticket in stuck:
        try:
            process_stuck_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing stuck {ticket['ticket_key']}: {e}")

    done = state.all_in_state("DONE")
    log(f"Checking {len(done)} done ticket(s) for review re-opens")
    for ticket in done:
        try:
            process_done_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing done {ticket['ticket_key']}: {e}")

    candidates = state.all_cleanup_candidates()
    log(f"Checking {len(candidates)} ticket(s) for worktree cleanup (terminal Jira status)")
    for ticket in candidates:
        try:
            process_cleanup_candidate(ticket)
        except Exception as e:
            log(f"ERROR cleaning up {ticket['ticket_key']}: {e}")


if __name__ == "__main__":
    main()
