#!/usr/bin/env python3
"""
aidev monitor — checks tickets in RUNNING state; when the tmux pane shows the
AIDEV_TASK_COMPLETE marker (or goes idle), moves them to POSTPROCESS: pushes
the branch, opens a PR via gh, and posts a summary comment back to Jira.

Also checks tickets in STUCK state; when Claude printed AIDEV_NEEDS_INPUT it
posts the question as a Jira comment and waits. Once a human replies on the
ticket (a comment that isn't one of aidev's own [aidev]-style comments), the
reply text is typed into the tmux session so Claude can continue.

Run this from cron (e.g. every 2-3 minutes), separate from pickup.py.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import config, jira_client, state, procs, lockfile
from lib.pipelog import get_logger
from lib.notify import notify

log = get_logger("monitor")

COMPLETE_RE = re.compile(r"⏺\s*AIDEV_TASK_COMPLETE")
NEEDS_INPUT_RE = re.compile(r"⏺\s*AIDEV_NEEDS_INPUT:\s*(.+)")


def is_complete(pane):
    return bool(COMPLETE_RE.search(pane))


def find_needs_input(pane):
    """Returns the most recent AIDEV_NEEDS_INPUT question in the pane, or None."""
    matches = NEEDS_INPUT_RE.findall(pane)
    return matches[-1].strip() if matches else None


def open_pr(ticket):
    cfg = config.load()
    worktree_path = ticket["worktree_path"]
    branch = ticket["branch"]
    key = ticket["ticket_key"]

    # Make sure everything is committed (Claude was instructed to commit,
    # but double-check / catch stragglers).
    procs.sh("git add -A", cwd=worktree_path, check=False)
    status = procs.sh("git status --porcelain", cwd=worktree_path, check=False)
    if status:
        msg = procs.shlex.quote(f"{key}: wip changes captured by aidev monitor")
        procs.sh(f"git commit -m {msg}", cwd=worktree_path, check=False)

    procs.sh(f"git push -u origin {branch}", cwd=worktree_path, check=False)

    base = cfg["pr"]["base_branch"]
    title = f"{key}: automated by aidev"
    body = f"Automated implementation for {key}.\n\nGenerated by Claude Code via aidev pipeline."
    pr_out = procs.sh(
        f'gh pr create --base {base} --head {branch} --title {procs.shlex.quote(title)} '
        f'--body {procs.shlex.quote(body)}',
        cwd=worktree_path, check=False,
    )
    pr_url = None
    for line in pr_out.splitlines():
        if line.startswith("https://"):
            pr_url = line.strip()
    return pr_url, pr_out


def mark_failed(key, reason, tmux_name=None):
    log(f"{key}: FAILED — {reason}")
    state.set_state(key, "FAILED")
    try:
        jira_client.add_comment(key, f"[aidev] Marked as failed: {reason}")
        jira_client.set_state_label(key, "aidev-stuck")
    except Exception as e:
        log(f"{key}: could not post failure comment: {e}")
    if tmux_name:
        procs.tmux_kill(tmux_name)
    notify(f"aidev: {key} failed", reason)


def process_running_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while RUNNING (crash, reboot, or manual kill)")
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"exceeded max_running_hours ({max_hours}h) — likely stuck in a loop or blocked silently",
            tmux_name=tmux_name,
        )
        return

    pane = procs.tmux_capture(tmux_name, lines=300)

    if is_complete(pane):
        log(f"{key}: task complete marker seen, waiting for idle before postprocess")
        procs.wait_for_idle(
            tmux_name,
            cfg["claude"]["idle_seconds"],
            cfg["claude"]["idle_poll_interval"],
            max_wait_seconds=300,
        )
        finish_ticket(ticket)
        return

    question = find_needs_input(pane)
    if question:
        log(f"{key}: needs input — {question}")
        state.set_stuck(key, question)
        try:
            jira_client.add_comment(
                key,
                f"[aidev] I need input to continue:\n\n{question}\n\n"
                f"Reply on this ticket and I'll pick it up on the next check.",
            )
            jira_client.set_state_label(key, "aidev-stuck")
        except Exception as e:
            log(f"{key}: could not post stuck comment: {e}")
        notify(f"aidev: {key} needs input", question)
        return

    log(f"{key}: still running")


def finish_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]

    state.set_state(key, "POSTPROCESS")
    log(f"{key}: opening PR")
    try:
        pr_url, pr_out = open_pr(ticket)
    except Exception as e:
        mark_failed(key, f"PR step failed: {e}")
        return

    state.set_state(key, "PR_OPENED", pr_url=pr_url)

    comment_lines = [f"\u2705 aidev finished {key}."]
    if pr_url:
        comment_lines.append(f"PR: {pr_url}")
    else:
        comment_lines.append(f"PR step output:\n{pr_out}")
    comment_lines.append(f"Worktree: {ticket['worktree_path']}")
    comment_lines.append(f"Session ID: {ticket['session_id']}")
    jira_client.add_comment(key, "\n".join(comment_lines))

    try:
        jira_client.transition_issue(key, cfg["jira"]["review_status"])
    except RuntimeError as e:
        log(f"{key}: transition warning: {e}")
    try:
        jira_client.set_state_label(key, "aidev-done")
    except Exception as e:
        log(f"{key}: label warning: {e}")

    state.set_state(key, "DONE", pr_url=pr_url)
    procs.tmux_kill(tmux_name)
    log(f"{key}: done")
    notify(f"aidev: {key} done", pr_url or "PR step had no URL — check comment")


def process_stuck_ticket(ticket):
    cfg = config.load()
    key = ticket["ticket_key"]
    tmux_name = ticket["tmux_session"]
    max_hours = cfg["claude"].get("max_running_hours")

    if not procs.tmux_session_exists(tmux_name):
        mark_failed(key, "tmux session disappeared while STUCK (crash, reboot, or manual kill)")
        return

    elapsed = state.seconds_running(ticket)
    if max_hours and elapsed and elapsed > max_hours * 3600:
        mark_failed(
            key,
            f"stuck waiting for a reply past max_running_hours ({max_hours}h) with no response",
            tmux_name=tmux_name,
        )
        return

    try:
        comments = jira_client.get_comments(key)
    except Exception as e:
        log(f"{key}: could not fetch comments: {e}")
        return

    if not comments:
        return

    last = comments[-1]
    body_text = jira_client.plain_description({"fields": {"description": last["body"]}})
    if body_text.strip().startswith("[aidev]"):
        # Last comment is our own — no human reply yet.
        return

    last_seen = ticket.get("last_comment_id")
    if last_seen == last["id"]:
        return

    log(f"{key}: human reply found — resuming session with the reply")
    procs.tmux_send(tmux_name, body_text.replace("\n", " "))
    state.set_last_comment_id(key, last["id"])
    state.clear_stuck(key)
    try:
        jira_client.set_state_label(key, "aidev-picked")
    except Exception as e:
        log(f"{key}: label warning: {e}")


def main():
    try:
        with lockfile.Lock("monitor"):
            _run()
    except lockfile.LockHeld as e:
        log(f"skip run: {e}")


def _run():
    running = state.all_in_state("RUNNING")
    log(f"Checking {len(running)} running ticket(s)")
    for ticket in running:
        try:
            process_running_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing {ticket['ticket_key']}: {e}")

    stuck = state.all_in_state("STUCK")
    log(f"Checking {len(stuck)} stuck ticket(s) for human replies")
    for ticket in stuck:
        try:
            process_stuck_ticket(ticket)
        except Exception as e:
            log(f"ERROR processing stuck {ticket['ticket_key']}: {e}")


if __name__ == "__main__":
    main()
